name: gwintech-landing
services:
- name: web
  github:
    repo: samarato/gwintech
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
